### ISSUE TITLE
Location sharing doesn't work

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#1047]
Location sharing doesn't seem to be working for anyone - need to diagnose and resolve

**Comment by tykennington** [comment]
I believe commit cfbc2bd should fix this, but it's hard to test without another steam player.

The problem was that the UI used to have a single checkbox for whether to share location with anyone, in addition selecting individual players. We got rid of this checkbox, so there was no way to activate location sharing. I removed that check so that it only looks at the per-player options + whether they're currently in the game.

**Comment by psyqotic** [comment]
From Austin: for sharing location worked with me and Mckay. To note when we logged off and logged back in we could still see each other when the sharing location wasn't marked anymore at that point.

**Comment by psyqotic** [comment]
The actual location sharing is working now, but there are a few things that need polished
https://streamable.com/oynn6u

- [x] If you enable send, you can't disable it without first disabling receive
- [x] If you turn off receive it doesn't turn it off, but if receive is off already when someone sends it works properly and you don't receive
- [x] Friend pins on the compass change size. Sometimes larger, then if you open the map and go back they shrink
![Image](https://github.com/user-attachments/assets/37e8165d-a3c4-4a36-b02c-a4cd12749fd0)
![Image](https://github.com/user-attachments/assets/5b967d4f-5e0c-4aa8-85ab-075002e892ee)
- [x] Rotate compass pins for friends 180 degrees so the point is down instead of up
- [x] Instead of friend pins always being green, add a pool of many colors that are randomly chosen from

**Comment by psyqotic** [comment]
Errors when trying to use location sharing today

![Image](https://github.com/user-attachments/assets/429a2f10-617e-4740-9660-93631c6deef1)

More errors and friend marker is white and stuck in place - doesn't move when you look around

![Image](https://github.com/user-attachments/assets/44028112-64f4-44c9-9dc5-6942af2bb979)

**Comment by psyqotic** [comment]
Unselecting "Send" still requires unselecting "Receive" first

**Comment by tykennington** [comment]
I believe I got the compass issue fixed in commit c40e932, and I stopped the weirdness with the send button (for real this time, I hope) in commit 1e78bb6. I verified that the buttons no longer turn back off by testing a client change in the editor connecting to the steam server, but I need a second player to test the compass change and make sure the map icons still show.

**Comment by tykennington** [comment]
Above issues fixed, but still working through an issue with refreshing the online/in-game statuses

**Comment by tykennington** [comment]
Fixed status refreshing in commit aac6853

**Comment by psyqotic** [comment]
Most is working properly. Now selecting/unselecting send/receive seems to get the player mixed up, and sometimes requires selecting/unselecting another player before the player you actually want
https://streamable.com/5uzbzo

**Comment by tykennington** [comment]
I think I found and fixed the issue with the receive checkbox (commit 400d2d4), but we need at least 3 people in at the same time to verify

**Comment by tykennington** [comment]
Player icon mix-up also fixed. Tested with McKay and Austin and no longer got that or the receive checkbox issue
