### ISSUE TITLE
Some map landmark icons not working

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#1347]
### Issue Details

- [ ] Not sure if script side or scene setup side, but tried toggling this icon on/off and it never displays for mines

![Image](https://github.com/user-attachments/assets/367dc60b-b946-44ea-8c6c-1dbb9ad8bdbf)

- [ ] We also still having missing icons on map

---

### Self Review (Complete After Assignment)

- [ ] Has task been reviewed for 100% Completion.
- [ ] All files modularly committed to Main/Beta Branch, with references to this ticket

_Set to "Needs Review" upon completion of above_

---

**Comment by psyqotic** [comment]
Portal marker also not working

![Image](https://github.com/user-attachments/assets/40989aee-8bf4-46f8-9819-88457bc5d039)

**Comment by tykennington** [comment]
Testing locally in a test scene, those toggles seem to work fine. Are we sure those features are set on those LocationVolumes and baked correctly?
But also the alignment is off and there's a dummy checkbox that aren't in the build. Git log isn't showing recent changes to Overlay-Map, so I'm not sure how that got in there and if someone made recent changes to it.

![Image](https://github.com/user-attachments/assets/e46ef70a-e71e-4750-b637-0dec1a397420)

**Comment by psyqotic** [comment]
@mckayrules need to do a pass through all the mine prebakes and make sure "Show On Map" is set to true

![Image](https://github.com/user-attachments/assets/1639e625-4a82-49d3-baf0-259dfcdba440)

**Comment by psyqotic** [comment]
Mines now show on the map, but portal icons are missing. Maybe portals didn't get rebaked?

![Image](https://github.com/user-attachments/assets/4fae2c03-4d67-43c3-a206-bfcfab5d9ea7)

**Comment by psyqotic** [comment]
Seems to be set up the exact same as a hamlet that is displaying both the name and icons properly on the map, but neither the portal name or icons are displaying

Portal:
![Image](https://github.com/user-attachments/assets/f9f31ac9-a5d4-4565-a8a8-d73262ce4586)

Homestead:
![Image](https://github.com/user-attachments/assets/cb9dd713-2c62-4950-bcb0-744b21b3de5b)

**Comment by psyqotic** [comment]
Vagrant icon is inconsistent - sometimes the horse (correct) sometimes a bowl (incorrect)

![Image](https://github.com/user-attachments/assets/5aee3e9e-7eea-41c7-a54f-45f74b86b5e0)

![Image](https://github.com/user-attachments/assets/e31e42d0-47bd-40fc-b55d-fd58d41052e9)

![Image](https://github.com/user-attachments/assets/090a77f7-6225-4faf-a240-66234c056bf6)

![Image](https://github.com/user-attachments/assets/75c3e136-fe19-496c-993c-89c7aff0217a)

**Comment by tykennington** [comment]
fixed icon inconsistencies in commit aec8ef5.
However, the "correct" one seemed to happen because the vagrant was outside the bounds of a location volume. I switched the grouped version to use correct icon (and made similar fixes for cook and stylist), but I'm not sure if the individual one was intended or if the location volume bounds need to be adjusted (or if this is another case of a location volume not registering at all)

**Comment by psyqotic** [comment]
- [ ] Icon tooltips are behind icons
- [ ] Portal icon still not showing (portal microstamp maybe needs rebaked?)
- [ ] Need additional icons for beacons, puzzle, other unique features

<img width="1920" height="1057" alt="Image" src="https://github.com/user-attachments/assets/b38dfa5b-27ea-4efa-b325-5fc8f43df6f7" />

**Comment by westonleavitt** [comment]
Closing this and reopening as its moved from the original ticket
