### ISSUE TITLE
Ocean boating

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#831]
Deploy boat > boat sinks/sticks to ocean floor > when I leave the boat I'm able to walk on the ocean floor > re-entering the boat causes it to float up to the surface and function properly (although it plays footstep audio on top of the rowing audio) > leaving the boat again re-entering the water volume is normal with swimming, etc.
https://streamable.com/muzgrn

**Comment by westonleavitt** [comment]
pretty sure this is fixed with the server adjustment to water. setting as needs verified

**Comment by tykennington** [comment]
Problem still present in current build, along with not being able to drown. Is the ocean collider still being stripped from the server?

**Comment by psyqotic** [comment]
These core issues seem to be fixed. There are some control and buoyancy issues now, but those are separate from these specific issues so I'm going to close.
